### ISSUE TITLE
Application error Flashbots.Console

### ISSUE THREAD

**Issue by yuratyp** [leonpw/Web3.Flashbots#1]
Simulation error: Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_callBundle
What could be the reason?

**Comment by leonpw** [comment]
Good morning,

Thank you for creating this issue. The flashbots RPC endpoint was ported to Golang and the types used in the payload got more strict. I updated the repository and created a new version!

**Comment by yuratyp** [comment]
Thanks for the help. You've helped me a lot.
